### ISSUE TITLE
No way to set index settings on replicas

### ISSUE THREAD

**Issue by timkelty** [riasvdv/craft-scout#114]
AFAIK, there is no way to currently set index settings on replicas.

I can add an `ScoutIndex` for my replica, and call `indexSettings` on it, and the `scout/settings/update` command works great.

However, if you then try and sync, you'll get an algolia error, because you aren't allowed to push objects to a replica index.

```
[2019-11-17 18:00:22] craftcms.ERROR: Algolia\AlgoliaSearch\Exceptions\BadRequestException: cannot apply a add object request on a replica index in /app/vendor/composer/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:210 Stack trace: #0 /app/vendor/composer/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(158): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->handleResponse(Object(GuzzleHttp\Psr7\Response), Object(Algolia\AlgoliaSearch\Http\Psr7\Request)) #1 /app/vendor/composer/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(92): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->request('POST', '/1/indexes/gear...', Object(Algolia\AlgoliaSearch\RequestOptions\RequestOptions), Array, 30, Array) #2 /app/vendor/composer/algolia/algoliasearch-client-php/src/SearchIndex.php(280): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->write('POST', '/1/indexes/gear...', Array, Object(Algolia\AlgoliaSearch\RequestOptions\RequestOptions)) #3 /app/vendor/composer/rias/craft-scout/src/engines/AlgoliaEngine.php(82): Algolia\AlgoliaSearch\SearchIndex->clearObjects() #4 /app/vendor/composer/rias/craft-scout/src/console/controllers/scout/IndexController.php(37): rias\scout\engines\AlgoliaEngine->flush() #5 /app/vendor/composer/tightenco/collect/src/Collect/Support/Collection.php(475): rias\scout\console\controllers\scout\IndexController->rias\scout\console\controllers\scout\{closure}(Object(rias\scout\engines\AlgoliaEngine), 1) #6 /app/vendor/composer/rias/craft-scout/src/console/controllers/scout/IndexController.php(39): Tightenco\Collect\Support\Collection->each(Object(Closure)) #7 /app/vendor/composer/rias/craft-scout/src/console/controllers/scout/IndexController.php(69): rias\scout\console\controllers\scout\IndexController->actionFlush('') #8 [internal function]: rias\scout\console\controllers\scout\IndexController->actionRefresh('') #9 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #11 /app/vendor/composer/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('', Array) #12 /app/vendor/composer/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array) #13 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array) #14 /app/vendor/composer/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('scout/index', Array) #15 /app/vendor/composer/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('scout/index', Array) #16 /app/vendor/composer/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('scout/index', Array) #17 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request)) #18 /app/bin/craft(7): yii\base\Application->run() #19 {main} {"trace":[],"memory":27655616,"category":"Algolia\\AlgoliaSearch\\Exceptions\\BadRequestException","exception":"[object] (Algolia\\AlgoliaSearch\\Exceptions\\BadRequestException(code: 403): cannot apply a add object request on a replica index at /app/vendor/composer/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:210)"} []
```

I even tried putting in a bogus criteria that would never match anything, but I still got the error:

```
        ScoutIndex::create('gearByPriceAsc')
            ->criteria(function (EntryQuery $query) {
                return $query->id(false);
            })
            ->indexSettings(
                (clone $baseGearIndexSettings)
                    ->customRanking([
                        'asc(price.min)',
                    ])
            ),
```

Couple of ideas for a fix:

- make `ScoutIndex::critiera` `null` by default, and bail on any object pushing
- add a `ScoutIndex::replica` boolean that prevented any object syncing
- Expand `IndexSettings` to accept more than just an array of strings. It could optionally be a nested set of `ScoutIndex`, whose settings would get synced with the `scout/settings/update` command. eg:

```
<?php
return [
  'indices' => [
    ScoutIndex::create('gear')
    ->attributesForFaceting([
      'reviewAverage',
      'price.min',
    ])
    ->indexSettings(
        IndexSettings::create()
        ->replicas([
            ScoutIndex::create('gearByPriceAsc')->customRanking(['asc(price.min)']),
            ScoutIndex::create('gearByPriceDesc')->customRanking(['desc(price.min)']),
            ScoutIndex::create('gearByReviewRatingAsc')->customRanking(['asc(reviewRating.min)']),
            ScoutIndex::create('gearByReviewRatingDesc')->customRanking(['desc(reviewRating.min)']),
        ])
    ),

  ]
];
```

The latter diverges the most from the Algolia Index setSettings API, but is probably the most useful for this use-case.

**Comment by riasvdv** [comment]
I think you're one of the few that's actually using this functionality, so to be honest I'll leave it up to you to decide what you think is the best solution.

I like the idea of a `->replicas` function on the indexSettings, that could encapsulate the logic for updating those nicely as well.

Would love a PR for this, make sure to add a test for it as well then.

**Comment by timkelty** [comment]
> I like the idea of a ->replicas function on the indexSettings, that could encapsulate the logic for updating those nicely as well.

It shall be done!

**Comment by riasvdv** [comment]
There was an error in the forwarding to replicas just fixed by @jalendport, but this feature can still be useful for setting distinct settings for each replica

**Comment by santi6291** [comment]
Curious, is this still in development or has it been released?

**Comment by timkelty** [comment]
@santi6291 I'm hoping to have a PR in the next week.

**Comment by rsanchez** [comment]
Any updates?

**Comment by timkelty** [comment]
hey looks its @rsanchez!

Perhaps that will inspire me to make good on my PR promise…thanks for the nudge.

**Comment by davist11** [comment]
👀 

any update on this? Definitely have a need on my current project.

**Comment by timkelty** [comment]
Thanks for the nudges…and sorry for the delays.
Up and had a baby and got a bit behind. 👶

Still on my list, and I'm looking at it tonight!

**Comment by davist11** [comment]
Dang babies, always getting in the way of everything 😂

**Comment by davist11** [comment]
Oh, and I forgot to say, let me know if I can help at all with testing.

**Comment by mgburns** [comment]
Just wanted to bump this one!

Our workaround:
- Define `indexSettings()` for each replica index in the `indices` config
- Comment them out whenever you're _not_ running `./craft scout/settings/update`

**Comment by tomdavies** [comment]
We would also love to see this fixed. Happy to take a shot at a PR if you're open to it

**Comment by janhenckens** [comment]
Hey @tomdavies, happy to review & test a PR if you'd like to get this done. Feel free to submit one and/or ping me on Discord if you'd like to discuss further.

**Comment by tomdavies** [comment]
@janhenckens I think this can be closed now that #275 is merged
