### ISSUE TITLE
Migration bug (going to v2.x)

### ISSUE THREAD

**Issue by lindseydiloreto** [riasvdv/craft-scout#138]
I'm updating Scout from `1.3.2` to `2.0.0`, and bumping into this migration issue. Not sure exactly what's causing it...

```
$ ./craft migrate/all

Exception 'Error' with message 'Class 'Tightenco\Collect\Support\Collection' not found'

in /vendor/rias/craft-scout/src/models/Settings.php:57

Stack trace:
#0 /vendor/rias/craft-scout/src/Scout.php(136): rias\scout\models\Settings->getIndices()
#1 /vendor/rias/craft-scout/src/Scout.php(66): rias\scout\Scout->validateConfig()
#2 /vendor/yiisoft/yii2/base/BaseObject.php(109): rias\scout\Scout->init()
#3 /vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 /vendor/craftcms/cms/src/base/Plugin.php(130): yii\base\Module->__construct('scout', Object(craft\console\Application), Array)
#5 [internal function]: craft\base\Plugin->__construct('scout', Object(craft\console\Application), Array)
#6 /vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#7 /vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('rias\\scout\\Scou...', Array, Array)
#8 /vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('rias\\scout\\Scou...', Array, Array)
#9 /vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#10 /vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('scout', Array)
#11 /vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\Plugins->loadPlugins()
#12 /vendor/craftcms/cms/src/console/Application.php(65): craft\console\Application->_postInit()
#13 /vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#14 /vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#16 /vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
#17 [internal function]: craft\console\Application->__construct(Array)
#18 /vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#19 /vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#20 /vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#21 /vendor/craftcms/cms/bootstrap/bootstrap.php(244): yii\BaseYii::createObject(Array)
#22 /vendor/craftcms/cms/bootstrap/console.php(33): require('/Users/lindseyd...')
#23 /craft(21): require('/Users/lindseyd...')
#24 {main}
```

**Comment by lindseydiloreto** [comment]
Weird, it seems like the `tightenco/collect` package isn't installed, even though Scout required it.

I guess we can blame this one on Composer! Thanks, and sorry for the false alarm! 👍

**Comment by timkelty** [comment]
I love to blame composer! But something odd seems up... a few other people are having trouble with the collection dep too... I’m guessing it’s some conflict with other packages

**Comment by lindseydiloreto** [comment]
Thanks for confirming @timkelty! So I guess it wasn't just me.

I noticed that when I copy the `tightenco/collect` up to the main composer.json file, everything loads as expected. But when I don't add it, and let composer rely on Scout's composer.json file, the `tightenco/collect` package doesn't get installed.

@timkelty If it were a conflict with other packages, wouldn't composer just yell & give up?

Thoughts @riasvdv? Did something change recently?

**Comment by timkelty** [comment]
>  If it were a conflict with other packages, wouldn't composer just yell & give up

Yup it should, but I've seen Composer do weirder things…

This seems like the same issue as https://github.com/riasvdv/craft-scout/issues/130, so lets track there.
