### ISSUE TITLE
Calling unknown method: craft\elements\GlobalSet::searchable()

### ISSUE THREAD

**Issue by jamesmacwhite** [riasvdv/craft-scout#142]
I've recently updated to Scout v2 and noticed when saving global settings I'm getting this error below.

It looks like Scout is intercepting the save event for Globals and calling `searchable()`, however this doesn't appear valid for GlobalSets in this case.

* Craft CMS: 3.3.20.1
* Plugin versions: 2.1.4
* PHP version: 7.2

***To reproduce:***

1. Install Scout v2.1.4
2. Go to a global set in the admin panel and save
3. Observe error below

```
yii\base\UnknownMethodException: Calling unknown method: craft\elements\GlobalSet::searchable() in /app/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /app/vendor/craftcms/cms/src/base/Element.php(1031): yii\base\Component->__call('searchable', Array)
#1 /app/vendor/rias/craft-scout/src/Scout.php(156): craft\base\Element->__call('searchable', Array)
#2 [internal function]: rias\scout\Scout->rias\scout\{closure}(Object(craft\events\ElementEvent))
#3 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#4 /app/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#5 /app/vendor/craftcms/cms/src/services/Elements.php(2092): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#6 /app/vendor/craftcms/cms/src/services/Elements.php(529): craft\services\Elements->_saveElementInternal(Object(craft\elements\GlobalSet), true, false)
#7 /app/vendor/craftcms/cms/src/controllers/GlobalsController.php(256): craft\services\Elements->saveElement(Object(craft\elements\GlobalSet))
#8 [internal function]: craft\controllers\GlobalsController->actionSaveContent()
#9 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /app/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save-content', Array)
#12 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-content', Array)
#13 /app/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('globals/save-co...', Array)
#14 /app/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('globals/save-co...', Array)
#15 /app/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /app/web/index.php(23): yii\base\Application->run()
#18 {main}
```

https://github.com/riasvdv/craft-scout/blob/master/src/Scout.php#L151-L159

**Comment by jamesmacwhite** [comment]
This turned out to be something else not related, where by globals had been broken and not initialised properly, because code somewhere else was breaking things!
