### ISSUE TITLE
CLI import throws exception when mapped field does not have a getIdPost method

### ISSUE THREAD

**Issue by philbarbato** [riasvdv/craft-scout#78]
Import is failing if a mapped field does not have a `getIsPost` method. In this instance, we're using [Easy Address Field](https://github.com/studioespresso/craft3-easyaddressfield), which does not have that method.

Config file: [scout.php.zip](https://github.com/riasvdv/craft-scout/files/3398711/scout.php.zip)

Error and stack trace below:

```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getIsPost()'

in /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /var/www/calendar-ochsner.test/vendor/studioespresso/craft-easyaddressfield/src/services/FieldService.php(79): yii\base\Component->__call('getIsPost', Array)
#1 /var/www/calendar-ochsner.test/vendor/studioespresso/craft-easyaddressfield/src/fields/EasyAddressFieldField.php(122): studioespresso\easyaddressfield\services\FieldService->getField(Object(studioespresso\easyaddressfield\fields\EasyAddressFieldField), Object(Solspace\Calendar\Elements\Event), NULL)
#2 /var/www/calendar-ochsner.test/vendor/craftcms/cms/src/base/Element.php(1937): studioespresso\easyaddressfield\fields\EasyAddressFieldField->normalizeValue(NULL, Object(Solspace\Calendar\Elements\Event))
#3 /var/www/calendar-ochsner.test/vendor/craftcms/cms/src/base/Element.php(793): craft\base\Element->normalizeFieldValue('locationDetails')
#4 /var/www/calendar-ochsner.test/config/scout.php(35): craft\base\Element->__get('locationDetails')
#5 [internal function]: craft\services\Config->{closure}(Object(Solspace\Calendar\Elements\Event))
#6 /var/www/calendar-ochsner.test/vendor/league/fractal/src/Scope.php(373): call_user_func(Object(Closure), Object(Solspace\Calendar\Elements\Event))
#7 /var/www/calendar-ochsner.test/vendor/league/fractal/src/Scope.php(315): League\Fractal\Scope->fireTransformer(Object(Closure), Object(Solspace\Calendar\Elements\Event))
#8 /var/www/calendar-ochsner.test/vendor/league/fractal/src/Scope.php(234): League\Fractal\Scope->executeResourceTransformers()
#9 /var/www/calendar-ochsner.test/vendor/rias/craft-scout/src/models/AlgoliaIndex.php(108): League\Fractal\Scope->toArray()
#10 /var/www/calendar-ochsner.test/vendor/rias/craft-scout/src/models/AlgoliaIndex.php(170): rias\scout\models\AlgoliaIndex->transformElement(Object(Solspace\Calendar\Elements\Event))
#11 /var/www/calendar-ochsner.test/vendor/rias/craft-scout/src/models/AlgoliaIndex.php(133): rias\scout\models\AlgoliaIndex->indexElement(Object(Solspace\Calendar\Elements\Event))
#12 /var/www/calendar-ochsner.test/vendor/rias/craft-scout/src/console/controllers/scout/IndexController.php(98): rias\scout\models\AlgoliaIndex->indexElements(Array)
#13 [internal function]: rias\scout\console\controllers\scout\IndexController->actionImport('')
#14 /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('import', Array)
#17 /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('import', Array)
#18 /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('scout/index/imp...', Array)
#19 /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('scout/index/imp...', Array)
#20 /var/www/calendar-ochsner.test/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /var/www/calendar-ochsner.test/craft(22): yii\base\Application->run()
#22 {main}
```

**Comment by riasvdv** [comment]
I think the issue is not in the Scout plugin, as the last thing Scout does is just calling this line

> #4 /var/www/calendar-ochsner.test/config/scout.php(35): craft\base\Element->__get('locationDetails')

I think the craft-easyaddressfield is trying to call `->getIsPost()` on the request, but because it is a console request this doesn't have this method.

@janhenckens This should be changed here https://github.com/studioespresso/craft3-easyaddressfield/blob/develop/src/services/FieldService.php#L81 to also check that it is not a console request.
